---
- name: Update Ubuntu and Install Resources on localhost
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install Python and packages
      apt:
        name:
          - python3-pip
          - figlet
          - postgresql-client
          - bash
          - python3-venv

- name: Install the app
  hosts: localhost
  tasks:
    - name: Copy app-src
      copy:
        src: /tmp/repo2/resources/lab/app-src
        dest: /home/ubuntu/lab-4

    - name: Copy requirements
      copy:
        src: /tmp/repo/requirements.txt
        dest: /home/ubuntu/lab-4

    - name: Install requirements
      command: "pip install -r /home/ubuntu/lab-4/requirements.txt"

    - name: Add environment variable & run Flask application in the background
      command: echo 'APP_TEMPLATE_PATH=/home/ubuntu/lab-4/app-src/index.html.jinja' | sudo tee -a /etc/environment > /dev/null
      command:  python3 /home/ubuntu/lab-4/app-src/mixologyfy.py > /dev/null 2>&1 &
      environment:
        VIRTUAL_ENV: /home/ubuntu/lab-4/venv

